### ISSUE TITLE
pebble-sdk: The formula should be built with system python

### ISSUE THREAD

**Issue by youtux** [youtux/homebrew-youtux#1]
Because of a bug with the particular configuration (gevent/requests/python-2.7.9) (see pebble/pypkjs#4), the formula should build `pebble-sdk` using the system version of python, namely `/usr/bin/python`, which in Yosemite is 2.7.6.

1) Although I can't see an easy way to do it, a simple approach is to substitute occurrences of `python` in the formula with `/usr/bin/python`.

But there is another problem: the `boost-python` dependency. This one breaks badly because the `pebble` script would be invoked using the system python (2.7.6), while `boost-python` is built against the brewed python (2.7.9), if present.

2) Is there a way to force `boost-python` to be compiled against the system python?

@tdsmith if you can help or if you have suggestions that would be really appreciated :)

**Comment by tdsmith** [comment]
Unlinking Homebrew python first would do it but you probably want something more robust.

The "real" solution is to discover whether it's possible and how to build boost-python in such a way that it doesn't link to libpython, using `-undefined dynamic_lookup`.

A workaround could be a keg-only `boost-python-system` or something that duplicates the boost-python formula without the `:python` dependency.

**Comment by youtux** [comment]
Thanks! I'll try that way.

**Comment by youtux** [comment]
Solved in c1f563b6a85f100315fc6152d4b45badbb200f2a.
